/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stddef.h>
#include <android/log.h>
/* Header for class com_github_controlx_jnindksample_MainActivity */

#ifndef _Included_com_github_controlx_jnindksample_MainActivity
#define _Included_com_github_controlx_jnindksample_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_controlx_jnindksample_MainActivity
 * Method:    MyNativeMethodStringType
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_controlx_jnindksample_MainActivity_MyNativeMethodStringType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_github_controlx_jnindksample_MainActivity
 * Method:    MyNativeMethodIntegerType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_github_controlx_jnindksample_MainActivity_MyNativeMethodIntegerType
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
