/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_github_controlx_jnindksample_MainActivity.h"

//JavaVM* gJvm = null;
static jobject gClassLoader;
static jmethodID gFindClassMethod;

/*
 * Class:     com_github_controlx_jnindksample_MainActivity
 * Method:    MyNativeMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_controlx_jnindksample_MainActivity_MyNativeMethodStringType(JNIEnv *env, jclass obj, jstring activityState){
    jstring constantString  = (*env)->NewStringUTF(env, "Activity state of this application is ");
    jstring dummySpace = (*env)->NewStringUTF(env, "=> ");

    jbyte *s1x  = (*env)->GetStringUTFChars(env, activityState, NULL);
    jbyte *s2x  = (*env)->GetStringUTFChars(env, constantString, NULL);
    jbyte *s3x  = (*env)->GetStringUTFChars(env, dummySpace, NULL);

    char *sall  = malloc(strlen(s1x) + strlen(s2x) + strlen(s3x) + 1);

    strcpy(sall, s2x);
    strcat(sall, s1x);
    strcat(sall, s3x);

    jstring retval = (*env)->NewStringUTF(env, sall);

    (*env)->ReleaseStringUTFChars(env, activityState, s1x);
    (*env)->ReleaseStringUTFChars(env, constantString, s2x);
    (*env)->ReleaseStringUTFChars(env, dummySpace, s3x);

    free(sall);

    return retval;
    //return (*env)->NewStringUTF(env, "Resumed status of this application:");
  }

JNIEXPORT jint JNICALL Java_com_github_controlx_jnindksample_MainActivity_MyNativeMethodIntegerType(JNIEnv *env, jclass obj, jint times){
        times = times + 1;
        return times;
  }

   JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* pVm, void* reserved)
   {
   __android_log_write(ANDROID_LOG_ERROR, "Tag", "Error here");
   JNIEnv* env; if ((*pVm)->GetEnv(pVm, (void **)&env, JNI_VERSION_1_6)) {
   return -1;
   }
   // Get jclass with env->FindClass.
    // Register methods with env->RegisterNatives.
     return JNI_VERSION_1_6;
   }

   /*JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *pjvm, void *reserved) {
       gJvm = pjvm;  // cache the JavaVM pointer
       auto env = getEnv();
       //replace with one of your classes in the line below
       auto randomClass = env->FindClass("com/example/RandomClass");
       jclass classClass = env->GetObjectClass(randomClass);
       auto classLoaderClass = env->FindClass("java/lang/ClassLoader");
       auto getClassLoaderMethod = env->GetMethodID(classClass, "getClassLoader",
                                                "()Ljava/lang/ClassLoader;");
       gClassLoader = env->CallObjectMethod(randomClass, getClassLoaderMethod);
       gFindClassMethod = env->GetMethodID(classLoaderClass, "findClass",
                                       "(Ljava/lang/String;)Ljava/lang/Class;");

       return JNI_VERSION_1_6;
   }

   jclass findClass(const char* name) {
       return static_cast<jclass>(getEnv()->CallObjectMethod(gClassLoader, gFindClassMethod, getEnv()->NewStringUTF(name)));
   }

   JNIEnv* getEnv() {
       JNIEnv *env;
       int status = gJvm->GetEnv((void**)&env, JNI_VERSION_1_6);
       if(status < 0) {
           status = gJvm->AttachCurrentThread(&env, NULL);
           if(status < 0) {
               return nullptr;
           }
       }
       return env;
   }*/